### ISSUE TITLE
TOP-app --> Automatische tests

### ISSUE THREAD

**Issue by peterboer** [Amsterdam/fixxx-looplijsten-backend#81]
De tests zullen voornamelijk voor de modellen en de APIs geschreven worden. Hiermee zal de meeste business logic getest zijn.

_Tests voor de functies voor het genereren van lijstjes kunnen nog uitgebreid worden_

Voor de Fraudpredict module zijn er nog geen tests, maar dat wordt straks en externe service van team CTO. 
Aangezien dit voorlopig nog een pilot is, en een deel van de functionaliteit verhuis naar de externe API zijn tests op dit moment niet heel urgent.

zie: https://trello.com/c/2IVkL3PN

**Comment by peterboer** [comment]
@petercuret wil jij deze ff checken en de overgebeleven tests naar Git meenemen?

**Comment by petercuret** [comment]
@peterboer ik heb je beschrijving aangevuld.
