### ISSUE TITLE
Top-app --> refactoring Backend

### ISSUE THREAD

**Issue by peterboer** [Amsterdam/fixxx-looplijsten-backend#82]
- [x] Safer case_detail view (try catches, etc)
- [ ] Check code for leftover TODO’s and Note’s

**Comment by peterboer** [comment]
@petercuret wil jij deze ff checken en de overgebeleven zaken in deze story plaatsen?

**Comment by petercuret** [comment]
@peterboer Ik heb de description bijgewerkt en de relevante items uit Trello hier in gezet.
