### ISSUE TITLE
Test aangepast Hitkans-model

### ISSUE THREAD

**Issue by peterboer** [Amsterdam/fixxx-looplijsten-backend#95]
Marius says: 'We hebben een versie van het model klaar om te testen, met verbeteerde shap values. Eer is een breaking change in de configuratie file, zie readme. Verder kunnen we nu bronnen aan en uitschakelen, zodat we dezelfde code base op de BI VAO (alle bronnen) en op de wonen VAO of in jullie omgeving kunnen gebruiken. Wij denken dat het werkt, maar laat ons graag weten zouden er problemen zijn. Als het goed is kunnen jullie na kleine aanpassingen in de config.yml het scoring code draaien. Dit is de commit (huidige versie van dev, maar die gaat verder ontwikkelen met nieuwe features, dus beter de commit has gebruiken: zie slackbericht: https://datalab-amsterdam.slack.com/archives/GU2F0SHM5/p1596113721003100

**Comment by petercuret** [comment]
Net een lokale test gedaan waar de hitkans berekeningen falen. De bwv database tabellen in de hitkans module worden nu allemaal aangesproken met een `bwv_` prefix, wat niet overeenkomt met de echt database. 
De gitlab met documentatie licht momenteel plat, wellicht staat hier iets over dit probleem. Verder is dit voorgelegd aan het hitkans team.

**Comment by peterboer** [comment]
done.
